### ISSUE TITLE
[BUG] Advanced Repair Kit

### ISSUE THREAD

**Issue by fileexists** [qbcore-framework/qb-mechanicjob#100]
**Describe the bug**
If i spawn a car with /car, i damage it a bit and then repair it using an advanced repair kit its repaired for me and everybody else ( even if im not a mechanic as a job ) but if somebody else repairs the car (even a mechanic) only he sees it repaired and not me

**To Reproduce**
1. Break your car a bit
2. Call a mechanic and make him use an advancedrepairkit
3. He will see the car fixed, but you wont

**Expected behavior**
It should be fixed when a mechanic repairs your car using a repairkit

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] 2 days ago
 - Are you using custom resource? which ones? NO, some custom cars, and a few scripts made by me but they dont interact with cars in that way
 - Have you renamed `qb-` to something custom? NO

**Comment by GhzGarage** [comment]
Sometimes there is a sync issue, i'm investigating it
