### ISSUE TITLE
[SUGGESTION] Apply Changes Rather Than Automatically Setting Them

### ISSUE THREAD

**Issue by uniqueorcaname** [qbcore-framework/qb-mechanicjob#114]
**Is your feature request related to a problem? Please describe.**
When selecting car modifications they apply automatically and sometimes you cannot undo those changes as the stock modification is not available. This forces you into keeping modifications on your car that you may only wanted to preview.

**Describe the feature you'd like**
Preview modifications and select again to apply those modifications. Also, don't consume the item used for upgrading if you didn't apply the customisation.

**Describe alternatives you've considered**
Undo system for car modifications which also doesn't consume the item unless you make a change.

**Additional context**
Items bought and used to trigger the menus for upgrading gets used regardless of whether you make any changes.

**Comment by Destructor** [comment]
Hi,

UP :+1:  

Only the performance can be deleted, for the other options is it possible to add this option?
