### ISSUE TITLE
vehicle status value not showing correctly.

### ISSUE THREAD

**Issue by vosscat** [qbcore-framework/qb-mechanicjob#25]
I have my engine value set as default which is ["body"] = 1000.0, I crashed my car pretty hard then get it on the lift. The status check message in chat says engine: 50/1000 which is only 5% left. But the status in qb-menu shows 50%/100%. So feels like somehow the  (if percentage > 100 then percentage = math.ceil(VehicleStatus[plate][k]) / 10) part not working correctly.

**Comment by GhzGarage** [comment]
Closed due to age
