### ISSUE TITLE
High SQL Query

### ISSUE THREAD

**Issue by Triga307** [qbcore-framework/qb-mechanicjob#30]
![image](https://user-images.githubusercontent.com/49097611/161995402-e9517194-edbe-44e1-8d9c-7c9acd2a1157.png)

Have been seeing this a lot. Any ways to improve?

**Comment by joewooddev1** [comment]
Unable to replicate after 30 minites of driving around and doing waypoints

**Comment by FjamZoo** [comment]
This is because A your server hosting is bad and needs upgraded or B you have too much traffic to handle I cannot reproduce this at all.
