### ISSUE TITLE
[BUG] Cant create multiple shops

### ISSUE THREAD

**Issue by ggoodell2** [qbcore-framework/qb-mechanicjob#39]
**Describe the bug**
cannot create multiple entries for exit, duty, stash and vehicles

**To Reproduce**
1. Go to config.lua
2. add vector3 coords for new shop(tried 3 different ways)
3. restart
4. only one shop works or none work

**Expected behavior**
multiple mechanic locations

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: 3 days ago
 - Are you using custom resource? which ones? mostly all stock qbcore
 - Have you renamed `qb-` to something custom? no

**Additional context**

**Comment by iktray** [comment]
#33

**Comment by imelero1995** [comment]
This isn't a bug, u must code it on your side, u can base on #33 to do it.
