### ISSUE TITLE
When repairing cars without losing materials

### ISSUE THREAD

**Issue by nylanpro** [qbcore-framework/qb-mechanicjob#5]
When repairing cars without losing materials, I am using the latest full file updated from txadmin
Video : https://streamable.com/q3w37m

**Comment by nylanpro** [comment]
Another video more specific about the error -> https://streamable.com/pn2awy

**Comment by flip4fzL** [comment]
Can confirm that you can repair and its not pulling the materials from the materials stash used for repairs.

**Comment by nylanpro** [comment]
yes. it only checks but doesn't remove when fix is ​​successful

**Comment by tkd129** [comment]
> Khi sửa xe không bị mất vật liệu, mình đang sử dụng full file mới nhất được cập nhật từ txadmin
> Video: https://streamable.com/q3w37m

ông cho tôi xon fb tôi có việc muốn hỏi

**Comment by nylanpro** [comment]
Thank @SW1FT

> yes. it only checks but doesn't remove when fix is ​​successful
