### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by klose2410** [qbcore-framework/qb-mechanicjob#56]
i update for some days ago and i cant interagt with any of the mechanic  i just bought advandce mechanic so that my mechanics still can fix cars   any idear?   have debug poly and all is fine  no consol fault  no F8 fault

**Comment by imelero1995** [comment]
I can't understand this, can explain better, provide any screenshot or video to check failure?

**Comment by ChristianBDev** [comment]
Are you still having this issue @klose2410
