### ISSUE TITLE
[BUG] canot interact with target

### ISSUE THREAD

**Issue by hybridgamer** [qbcore-framework/qb-mechanicjob#57]
canot set myself on duty evrything is broken after update artifact 6004

**Comment by imelero1995** [comment]
Can you provide a video to try reproduce steps?

**Comment by Redneckslandei** [comment]
You don't see any interaction anymore! Even tuning is no longer possible! No error message!

**Comment by Redneckslandei** [comment]
https://www.youtube.com/watch?v=NLAYdavYYL8

**Comment by DustyBoy2** [comment]
@Redneckslandei did you find a solution? I am having the same problem.

**Comment by ChristianBDev** [comment]
> 

Were you on Duty?

**Comment by Glen92** [comment]
did you find a fix for this?

**Comment by ChristianBDev** [comment]
> canot set myself on duty evrything is broken after update artifact 6004

You restarted/ensured the resource, once you refresh then ensure or restart the script, you have to logout, then go back to clock on duty, I made a onResourceStart function that is waiting to be merged.

**Comment by ChristianBDev** [comment]
@Glen92 ^

**Comment by Sharkiiie** [comment]
Has this been resolved?
If so, please close the issue!
