### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ronhillgaming** [qbcore-framework/qb-mechanicjob#58]
Not sure if this is a bug or not but I cannot seem to add any additional locations for the mechanic shop. I would like a second location at Otto's Autos and when I tried to add coordinates for additional pads and the coordinates for "duty", "stash", etc. I get an error Error loading script config.lua in resource qb-mechanicjob: @qb-mechanicjob/config.lua:5: attempt to index a nil value (global 'Config')
[script:qb-mechanicjo] stack traceback:
[script:qb-mechanicjo] 	@qb-mechanicjob/config.lua:5: in main chunk

Obviously, there is nothing in line 5 that is touched and there are no other syntax errors in the script (all brackets and commas are correct). My question is: Is it possible to add additional locations to the qb-mechanicshop script? Thank you for your time.

**Comment by imelero1995** [comment]
Can u provide example of files and screenshots? Check your fxmanifest.lua if got added "shared_scripts" and calls fine to Config File

**Comment by ChristianBDev** [comment]
@ronhillgaming  You still having problems, if so please Can u provide example of files and screenshots? Check your fxmanifest.lua if got added "shared_scripts" and calls fine to Config File
