### ISSUE TITLE
[BUG] Tow truck not working

### ISSUE THREAD

**Issue by nzkfc** [qbcore-framework/qb-mechanicjob#62]
**Describe the bug**
Might be related to this: https://github.com/qbcore-framework/qb-towjob/issues/58#issue-1498010974

Flatbed won't put car on the back

**To Reproduce**
1. Get mechanic job
2. Get tow truck
3. Try put a car on the back via F1 radial menu

**Expected behavior**
Car goes on back

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: 100% fresh qb-core city today
 - Are you using custom resource? which ones? Default recipie
 - Have you renamed `qb-` to something custom? no

**Additional context**
I've tried this on gamebuild 2545 and 2699 and happens on both.

**Comment by mwuhahaa** [comment]
Still not working.
