### ISSUE TITLE
[BUG] Items in stash not being removed after fixing a vehicle

### ISSUE THREAD

**Issue by ShomyTKD** [qbcore-framework/qb-mechanicjob#63]
**Describe the bug**
When repairing a vehicle as a mechanic, you should be using the items inside mechanic's stash. However, once the vehicle is fixed, items don't get removed from the stash since the event SaveStashItems doesn't exist in qb-inventory anymore.

**To Reproduce**
1. As a mechanic, make sure first that you have enough materials in the stash.
2. Go and attach a vehicle to the lift and fix it's body for example.
3. Go back to your stash and you will notice that the materials used haven't been removed.

**Expected behavior**
After fixing a vehicle, stash should update it's items.

**Screenshots**
N/A

**Questions (please complete the following information):**
 - When you last updated: Today
 - Are you using custom resource? which ones? No, I am pressing E for access
 - Have you renamed `qb-` to something custom? No

**Additional context**
N/A

**Comment by Matetv** [comment]
server
```
RegisterNetEvent('qb-inventory:server:SaveStashItems', function(stashId, items)
    MySQL.Async.insert('INSERT INTO stashitems (stash, items) VALUES (:stash, :items) ON DUPLICATE KEY UPDATE items = :items', {
        ['stash'] = stashId,
        ['items'] = json.encode(items)
    })
end)
```
