### ISSUE TITLE
Cannot interact with anything since the update

### ISSUE THREAD

**Issue by davoucci** [qbcore-framework/qb-mechanicjob#70]
i've updated the script (1.0.0 to 2.1.1) and since that i cannot see the plates.. I did put the debug poly to true and the polyzone are there... i don't got any errors.

**Comment by ChristianBDev** [comment]
> i've updated the script (1.0.0 to 2.1.1) and since that i cannot see the plates.. I did put the debug poly to true and the polyzone are there... i don't got any errors.

Is the core updated fully or on the old core? You also have to have the job and be on duty, but if you restart, until my pr(Pull Request) comes out, you need to /logout and then log back in and then go back on duty to maybe see plates, the debugger may or may not work, I have to take a look at that.

**Comment by Sharkiiie** [comment]
Has this been resolved?
If so, please close the issue.
