### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by MFKR666** [qbcore-framework/qb-mechanicjob#71]
How do the finances work in this one?

How does a mechanic ask a customer to pay for everything?
Where does the money go, in mechanics pocket or in bossmenu vault?

**Comment by Sharkiiie** [comment]
qb-mechanicjob does not contain any code pertaining to charging other players.

It is up to you or the players to decide how you want to handle payments.
They can accept cash, or you can use an invoicing script, or qb-phone, I suppose.
