### ISSUE TITLE
cars automatically catches fire while driving [BUG]

### ISSUE THREAD

**Issue by Your-Spy** [qbcore-framework/qb-mechanicjob#91]

**Comment by amirhosin0554** [comment]
Hi i haved this problem like you 
For disabled this go into qb-mechanic config const.lua 
You can find at first Config.ignoreClass 
Type class of vehicle to disable damage 
For ex [18] = true,  -- Emergency 



Or you can do this ---not recomended
Go mechanicjob client drivingdistance.lua 

Delete line 90 - 94

**Comment by xNazz** [comment]
no need to delete code, just set Config.UseDistanceDamage to false
