### ISSUE TITLE
[BUG] Can not use this resource

### ISSUE THREAD

**Issue by TMSdot** [qbcore-framework/qb-mechanicjob#94]
**Describe the bug**
We installed FX server with QB core framework freshly, and after the installation it seems that the server is working, but after we set the job type to mechanic the resource is not working. The issue is I can't do anything in LS customs and Benny's Workshop, I mean the duty function and others are not working. If I want to go on duty or off duty then at the duty point, I can't do it. If I crash a car and goes to the LS customs, then I drove the car to the repair area, then also nothing happens. Same issue with the Benny's workshop. 

We have read the documentation, but we don't know that we do something wrong, or this is a bug.

**Comment by TMSdot** [comment]
The documentation not says that i have to use the "alt" button, this is a key moment to go on duty or off duty or to other function. But after we found that if you put an item or more to the Benny's stash (, we haven't tested the stash at the LS customs), and after, when I close the stash and re open it, then the items dissapears.

**Comment by GhzGarage** [comment]
Stash fix https://github.com/qbcore-framework/qb-mechanicjob/commit/5e43b780df47f425ed790cc22b20e4e1d56b2370

**Comment by GhzGarage** [comment]
For you first reported issue, there are shops setup at each location to buy parts to use on the vehicles
