### ISSUE TITLE
[BUG] HHHHHELP

### ISSUE THREAD

**Issue by OTH0A** [qbcore-framework/qb-mechanicjob#96]
**Describe the bug**

https://media.discordapp.net/attachments/1188223313118507100/1193571978167197826/image.png?ex=65ad3387&is=659abe87&hm=19520a66848ac39bb7142c97480ebb461dc87e0bf1b4c5868ad161572be24858&=&format=webp&quality=lossless

https://media.discordapp.net/attachments/1188223313118507100/1193576622796837025/image.png?ex=65ad37da&is=659ac2da&hm=d68b8b1f98208942c1cc1d757f4cff02f88ce83a978132526485737a2499105e&=&format=webp&quality=lossless&width=512&height=676

**Comment by OTH0A** [comment]
pllz help

**Comment by GhzGarage** [comment]
discord.gg/qbcore
